# Copyright (c) 2018, ARM Limited.
# SPDX-License-Identifier: Apache-2.0

ARG ARM_ARCH=arm64v8
FROM ${ARM_ARCH}/ubuntu:focal

COPY ./qemu-user-static/* /usr/bin/

COPY ./sources.list /etc/apt

# Set timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && apt-get install -q -y tzdata && rm -rf /var/lib/apt/lists/*

RUN apt update

# ROS2 dependencies
RUN apt update && apt install -y --no-install-recommends \
    build-essential \
    libbullet-dev   \
    libasio-dev 

RUN apt update && apt install --no-install-recommends -y \
    libtinyxml2-dev \
    sqlite3 \
    libsqlite3-dev \
    libeigen3-dev \
    liblog4cxx-dev \
    libcurl4-openssl-dev \
    python3.8 \
    python3-dev \
    libboost-dev \
    libboost-date-time-dev \
    libboost-thread-dev 

WORKDIR /
RUN apt-get install -y symlinks
RUN symlinks -rc .
